### ISSUE TITLE
ODROID-C1 pin mapping

### ISSUE THREAD

**Issue by vitzli** [mlinuxguy/WiringPi2-odroid-c1#1]
It is not an issue really, but I've made a pin mapping for C1 [odroid-c1-pinmap.pdf](https://mega.co.nz/#!l44AGKAI!OsiE_Nga1Hrlwhck4h93Aaeh9we5OKg9HZk2TvrSB2k)

**Comment by mlinuxguy** [comment]
Nice map

**Comment by mlinuxguy** [comment]
I pushed your PDF into the repo,  Thanks!
